name: Java

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build
        run: mvn --batch-mode -DskipTests package
      - name: Test
        run: mvn --batch-mode test

  telegram_success:
    if: success()
    needs: [ build ]
    name: Telegram_success
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            Status: all tests passed
    telegram_failure:
      if: failure()
      needs: [ build ]
      name: Telegram_failure
      runs-on: ubuntu-latest
      steps:
        - name: send telegram message on push
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_ID }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            message: |
              ${{ github.actor }} created commit:
              Commit message: ${{ github.event.commits[0].message }}
              Repository: ${{ github.repository }}
              Status: some tests are failing